DROP TABLE IF EXISTS Laureate, Org, Prize;

CREATE TABLE Org(
id INT PRIMARY KEY,
orgName VARCHAR(150) NULL DEFAULT NULL,
founded_date DATE NULL DEFAULT NULL,
founded_city VARCHAR(50) NULL DEFAULT NULL,
founded_country VARCHAR(50) NULL DEFAULT NULL
);

CREATE TABLE Laureate(
id INT PRIMARY KEY,
givenName VARCHAR(100) DEFAULT NULL,
familyName VARCHAR(100) DEFAULT NULL,
gender VARCHAR(10) DEFAULT NULL,
birth_date DATE DEFAULT NULL,
birth_city VARCHAR(100) DEFAULT NULL,
birth_country VARCHAR(100) DEFAULT NULL
);

CREATE TABLE Prize(
id INT,
awardYear VARCHAR(5),
category VARCHAR(50),
sortOrder VARCHAR(2),
affiliation_name VARCHAR(100),
affiliation_city VARCHAR(100) DEFAULT NULL,
affiliation_country VARCHAR(100) DEFAULT NULL
);

LOAD DATA LOCAL INFILE './org.del' INTO TABLE Org FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE './laureate.del' INTO TABLE Laureate FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE './prize.del' INTO TABLE Prize FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
